### ISSUE TITLE
Replace OpenID with SAML auth

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/sagexit#1]
As [per March 1st 2021, the Science OpenID server will be terminated](https://wiki.cncz.science.ru.nl/Nieuws#End_of_Science_OpenID_service), we need to find a replacement. CNCZ announced that they will be using SAML as alternative, which should be fairly easy for us to implement (https://pypi.org/project/django-saml2-auth/). We only need to wait for CNCZ to respond to our request whether we can use it

**Comment by JobDoesburg** [comment]
Update: CNCZ replied that they are still thinking about a solution...

**Comment by SebastiaanSafeguard** [comment]
@JobDoesburg is cncz providing saml or is it the uni wide SAML solution?

**Comment by se-bastiaan** [comment]
@JobDoesburg Is C&CZ providing SAML or is this the uni-wide SAML solution?

**Comment by JobDoesburg** [comment]
I'm currently using the C&CZ SAML. C&CZ replied that they would be interested to use us as a test-case for third parties to use SAML (and it looks like everything is working, I'm only waiting for them to whitelist us)
