### ISSUE TITLE
Anchor edges of reserved timeslots/allow us to shorten timeslots

### ISSUE THREAD

**Issue by mgullit** [svthalia/sagexit#20]
- Right now if you reserve a timeslot from say 09:00 - 16:00 you reserve a 7-hour slot in Mercator. Which is fine and it works perfectly
- However I was in the situation that I wanted to _shorten_ my reservation for tomorrow from 09:00-16:00 to 12:00-16:00. If I tried to drag down the slot from 09:00 to 12:00, I got an error saying I needed to reserve between 08:00 and 18:00. Which makes sense becase a 7-hour slot would go from 12:00 to 19:00 and that would not work
- Maybe it's an idea to anchor the two ends of the slots so they can be shortened and extended at will without moving the whole slot? So in my case, the slot was set from 09:00-16:00 and it by dragging the top end from 09:00 to 12:00 the bottom end would stay at 16:00 instead of trying to move to 19:00, therefore retaining the original time allocation of 7 hours

**Comment by JobDoesburg** [comment]
Sadly fullcalendar.io does not support this (although they do offer a setting that seems to enable this, it does not work)

**Comment by mgullit** [comment]
Fullcalendar.io has to trek an ad

Op ma 22 mrt. 2021 16:51 schreef Job Doesburg ***@***.***>:
