### ISSUE TITLE
Allow multiple reservations per room

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/sagexit#8]
Right now the app allows only a single reservation at a time for a specific slot. We should change this to allow at most **x** reservations for a specific room at a time. That works more intuitive for users

**Comment by se-bastiaan** [comment]
I think this issue means that you want to have a maximum number of registrations per room instead of max one registration per room, since this is currently circumvented by setting this the spots up as different rooms. Correct? I had a hard time reading the description.

**Comment by JobDoesburg** [comment]
Yes.
